# Example from The Java Tutorials: Implementing Your Own Permission
# http://docs.oracle.com/javase/tutorial/security/userperm/index.html

run:
	java -cp "game:score" -Djava.security.manager -Djava.security.policy=kim.policy com.gamedev.games.ExampleGame get 123

build:
	javac */com/scoredev/*/*.java

